#!/bin/bash

check_package_manager_running_helper() {
   trap "error_handler" ERR

   if [ -f "/var/run/package_manager_lock" ]; then
      check_apt_get_exit_code="/var/run/package_manager_lock exists."
      package_manager_waiting_msg="Lock file \
/var/run/package_manager_lock exists. Waiting for it to be removed..."
      return 0
   fi

   check_apt_get_exit_code="0"
   sudo  "/usr/lib/anon-shared-helper-scripts/apt-get-update-simulate" >/dev/null 2>&1 &
   apt_get_update_pid="$!"
   wait "$apt_get_update_pid" || { check_apt_get_exit_code="$?" ; true; };
   unset apt_get_update_pid

   if [ ! "$check_apt_get_exit_code" = "0" ]; then
      package_manager_waiting_msg="A package manager is currently running.
(\"apt-get dist-upgrade --simulate\" exit code: $check_apt_get_exit_code)
Waiting for it to finish..."
   else
      package_manager_waiting_msg="No package manger currently running. \
You should not see this message. Please report this bug!"
   fi
}
