#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -e

## provides: check_tor_bootstrap_helper_variables
source /usr/lib/anon-shared-helper-scripts/tor_bootstrap_check.bsh

check_tor_bootstrap_helper_variables

echo "\
TOR_CONTROL_HOST=\"$TOR_CONTROL_HOST\"
TOR_CONTROL_AUTHENTICATE=\"$TOR_CONTROL_AUTHENTICATE\"
TOR_CONTROL_PORT=\"$TOR_CONTROL_PORT\""
