#!/bin/bash

## Copyright (C) 2012 - 2018 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x
set -e

if command -v qubesdb-read ; then
   konsole -e "$@"
else
   konsole --fullscreen -e "$@"
fi
