#!/bin/bash

## Copyright (C) 2012 - 2018 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x
set -e

if command -v konsole_ >/dev/null 2>&1; then
   terminal_emulator_app="konsole"
elif command -v xterm_ >/dev/null 2>&1; then
   terminal_emulator_app="xterm -e"
else
   error_message="$0: No supported terminal_emulator_app installed! Please install either konsole or xterm. parent:

PPID: $PPID
$0 was called by: $(ps --no-headers -o command $PPID)" || true
   kdialog --sorry "$error_message" || true
   zenity --error --text "$error_message" || true
   echo "$error_message" >&2
fi

if command -v qubesdb-read >/dev/null 2>&1; then
   ## Qubes.
   if [ "$terminal_emulator_app" = "konsole" ]; then
      terminal_emulator_extra_args="--hold -e"
   fi
else
   ## Non-Qubes.
   if [ "$terminal_emulator_app" = "konsole" ]; then
      terminal_emulator_extra_args="--hold -e --fullscreen"
   fi
fi

$terminal_emulator_app $terminal_emulator_extra_args "$@ ; bash"
