#!/bin/bash

## Copyright (C) 2012 - 2018 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x
set -e

if command -v konsole >/dev/null 2>&1; then
   [ -n "$terminal_emulator_app" ] || terminal_emulator_app="konsole"
elif command -v xfce4-terminal >/dev/null 2>&1; then
   [ -n "$terminal_emulator_app" ] || terminal_emulator_app="xfce4-terminal"
elif command -v xterm >/dev/null 2>&1; then
   [ -n "$terminal_emulator_app" ] || terminal_emulator_app="xterm"
else
   error_message="$0: No supported terminal_emulator_app installed! Please install either konsole or xterm. parent:

PPID: $PPID
$0 was called by: $(ps --no-headers -o command $PPID)" || true
   kdialog --sorry "$error_message" >/dev/null 2>&1 || true
   zenity --error --text "$error_message" >/dev/null 2>&1 || true
   echo "$error_message" >&2
fi

if [ "$terminal_emulator_app" = "xfce4-terminal" ]; then
   [ -n "$terminal_emulator_extra_args" ] || terminal_emulator_extra_args="--execute"
fi

if [ "$terminal_emulator_app" = "xterm" ]; then
   [ -n "$terminal_emulator_extra_args" ] || terminal_emulator_extra_args="-e"
fi

if command -v qubesdb-read >/dev/null 2>&1; then
   ## Qubes.
   if [ "$terminal_emulator_app" = "konsole" ]; then
      [ -n "$terminal_emulator_extra_args" ] || terminal_emulator_extra_args="--hold -e"
   fi
else
   ## Non-Qubes.
   if [ "$terminal_emulator_app" = "konsole" ]; then
      [ -n "$terminal_emulator_extra_args" ] || terminal_emulator_extra_args="--hold -e --fullscreen"
   fi
fi

$terminal_emulator_app $terminal_emulator_extra_args $@
