#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

check_tor_enabled_do() {
   ## Skip this test, if not running on Whonix-Gateway.
   if [ ! -e "/usr/share/anon-gw-base-files/gateway" ]; then
      TOR_ENABLED="1"
      return 0
   fi

   ## Skip this test, if running in Qubes TemplateVM.
   if command -v qubesdb-read >/dev/null 2>&1 ; then
      local qubes_vm_type
      qubes_vm_type="$(qubesdb-read /qubes-vm-type)" || true
      if [ "$qubes_vm_type" = "TemplateVM" ]; then
         TOR_ENABLED="1"
         return 0
      fi
   fi

   if [ ! -e "/etc/tor/torrc" ]; then
      error "check_tor_enabled: file /etc/tor/torrc does not exist."
      TOR_ENABLED="0"
      return 0
   fi

   local line

   ## Parse /etc/tor/torrc.
   while read -r line || [ -n "$line" ]; do
      if [ "$line" = "DisableNetwork 0" ]; then
         TOR_ENABLED="1"
         return 0
      fi
   done < "/etc/tor/torrc"
   unset line

   ## Parse /usr/share/tor/tor-service-defaults-torrc.
   while read -r line || [ -n "$line" ]; do
      if [ "$line" = "DisableNetwork 0" ]; then
         TOR_ENABLED="1"
         return 0
      fi
   done < "/usr/share/tor/tor-service-defaults-torrc"
   unset line

   ## Fallback.
   TOR_ENABLED="0"
   return 0
}
