#!/bin/bash

## Copyright (C) 2012 - 2018 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

check_tor_enabled_do() {
   ## Fallback.
   TOR_ENABLED="0"

   ## Skip this test, if not running on Whonix-Gateway.
   if [ ! -e "/usr/share/anon-gw-base-files/gateway" ]; then
      TOR_ENABLED="1"
      return 0
   fi

   ## Skip this test, if running in Qubes TemplateVM.
   if command -v qubesdb-read >/dev/null 2>&1 ; then
      local qubes_vm_type
      qubes_vm_type="$(qubesdb-read /qubes-vm-type)" || true
      if [ "$qubes_vm_type" = "TemplateVM" ]; then
         TOR_ENABLED="1"
         return 0
      fi
   fi

   shopt -s globstar
   shopt -s nullglob

   ## many function calls in this script are provided by torrc-parser
   ## provides: get_tor_start_command
   ## provides: and extra_specified_torrc
   ## provides: value_of_disable_network
   source /usr/lib/anon-shared-helper-scripts/torrc-parser

   ## sets: $tor_start_command
   get_tor_start_command

   ## extract default_torrc file and -f torrc file
   ## sets: $default_torrc
   ## sets: $f_torrc
   extra_specified_torrc

   ## call parser() to parse torrc files, arguments order matters
   ## $torrc_all_in_one is set by the call
   parser "$default_torrc" "$f_torrc"

   ## The $TOR_ENABLED is used by whonixcheck
   ## sets: $TOR_ENABLED
   value_of_disable_network
}
