#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

if [ "$DEBDEBUG" = "1" ]; then
   set -x
fi

if [ "$DEBDEBUG" = "1" ]; then
   true "LD_PRELOAD: $LD_PRELOAD"
fi

## Remove /usr/lib/torsocks/libtorsocks.so from LD_PRELOAD.
LD_PRELOAD="$(echo "$LD_PRELOAD" | sed 's/\/usr\/lib\/torsocks\/libtorsocks.so//g')"

if [ "$DEBDEBUG" = "1" ]; then
   true "exit code: $?"
fi

export LD_PRELOAD

if [ "$DEBDEBUG" = "1" ]; then
   true "exit code: $?"

   true "LD_PRELOAD: $LD_PRELOAD"
fi

## Don't use exit at the end, since this script can be sourced by others.
