#!/bin/bash

## Copyright (C) 2012 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

set -o errexit
set -o nounset
set -o errtrace
set -o pipefail

pidfile="/run/helper-scripts/security-misc-apt-get-update-pid"

if ! test -f "$pidfile" ; then
  true "$0: INFO: pidfile $pidfile does not exist, ok."
  exit 0
fi

start-stop-daemon --stop --quiet --retry=TERM/5/KILL/5 --pidfile "$pidfile"

exit 0
