#!/bin/bash

## Copyright (C) 2025 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

set -o errexit
set -o nounset
set -o pipefail
set -o errtrace
shopt -s inherit_errexit
shopt -s shift_verbose

network_ip_data="$(
  ip -o addr show scope global \
  | awk '{print $4}'
)" || true
if [ -n "${network_ip_data}" ]; then
  exit 0
fi
exit 1
