#!/bin/bash

## Copyright (C) 2012 - 2023 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

## Script to simplify testing Xfce settings files.

set -x
set -e

sudo systemctl stop gdm3
sudo killall xfconfd || true
sleep 2

sudo rm --verbose --force /home/user/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml

if test -f /home/user/new ; then
   cp --verbose /home/user/new /home/user/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml
else
   cp --verbose /etc/skel/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml /home/user/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml
fi

chown --verbose user:user /home/user/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml

sudo systemctl restart gdm3
