#!/bin/bash

## Copyright (C) 2021 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

PROJECT_NAME="$(cat /etc/dpkg/origins/default | grep "Vendor:" | awk '{print $2}')"
PROJECT_HOMEPAGE="$(cat /etc/dpkg/origins/default | grep "Vendor-URL:" | awk '{print $2}')"

if test -r /etc/whonix_version ; then
   derivative_major_release_version="$(cat "/etc/whonix_version")"
elif test -r /etc/kicksecure_version ; then
   derivative_major_release_version="$(cat "/etc/kicksecure_version")"
fi
