#!/bin/bash

## Copyright (C) 2012 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

#set -x
set -o errexit
set -o nounset
set -o errtrace
set -o pipefail

true "$0: START"

source "${HELPER_SCRIPTS_PATH:-}"/usr/libexec/helper-scripts/pre.bsh

#disable_echo

printf '%s\n' "test"

#enable_echo

false

true "$0: END"
