#!/bin/bash

## Copyright (C) 2017 - 2021 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

set -e

/usr/libexec/helper-scripts/settings_echo > /run/helper-scripts/settings_environment_file
