#!/bin/bash

## Copyright (C) 2025 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

set -o errexit
set -o nounset
set -o errtrace
set -o pipefail

output="$(timeout --kill-after="1" "5" systemctl --wait is-system-running 2>&1)"

overwrite /run/helper-scripts/system-ready-check "$output" >/dev/null
