#!/bin/bash

## Copyright (C) 2025 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

set -o errexit
set -o nounset
set -o errtrace
set -o pipefail

if output="$(timeout --kill-after="1" "5" systemctl --wait is-system-running 2>&1)" ; then
  printf '%s\n' "$output"
  exit_code=0
else
  printf '%s\n' "$output" >&2
  exit_code=1
fi

exit "$exit_code"
