#!/bin/bash

## Copyright (C) 2025 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

source /usr/libexec/helper-scripts/package_installed_check.bsh

sysmaint_need_mode="${1:-needs-sysmaint}"

kernel_cmdline=""
if [ -r '/proc/cmdline' ]; then
  kernel_cmdline="$(cat -- /proc/cmdline)"
elif [ -r '/proc/1/cmdline' ]; then
  kernel_cmdline="$(cat -- /proc/1/cmdline)"
fi

if ! pkg_installed user-sysmaint-split; then
  true "$0: Package user-sysmaint-split installed: no - Therefore, exit 0."
  exit 0
fi
true "$0: Package user-sysmaint-split installed: yes"

if [[ "${kernel_cmdline}" =~ 'boot-role=sysmaint' ]]; then
  true "$0: kernel_cmdline contains boot-role=sysmaint: yes"
  if [ "${sysmaint_need_mode}" = 'needs-user' ]; then
    true "$0: sysmaint_need_mode: needs-user - Therefore, exit 1."
    exit 1
  fi
else
  true "$0: kernel_cmdline contains boot-role=sysmaint: no"
  if [ "${sysmaint_need_mode}" = 'needs-sysmaint' ]; then
    true "$0: sysmaint_need_mode: needs-sysmaint - Therefore, exit 1."
    exit 1
  fi
fi

true "$0: Default - Therefore, exit 0."
exit 0
