.\" generated with Ronn-NG/v0.10.1
.\" http://github.com/apjanke/ronn-ng/tree/0.10.1
.TH "ANON\-CONSENSUS\-DELETE" "8" "January 2020" "helper-scripts" "helper-scripts Manual"
.SH "NAME"
\fBanon\-consensus\-delete\fR \- Tor consensus deletion
.SH "SYNOPSIS"
\fBanon\-consensus\-delete\fR
.SH "DESCRIPTION"
\fBanon\-consensus\-delete\fR is a user\-friendly wrapper that deletes all Tor consensus files\.
.SH "AUTHOR"
This man page has been written by Patrick Schleizer (adrelanos@whonix\.org)
