.\" generated with Ronn-NG/v0.8.0
.\" http://github.com/apjanke/ronn-ng/tree/0.8.0
.TH "WATCH" "8" "January 2020" "helper-scripts" "helper-scripts Manual"
.SH "NAME"
\fBwatch\fR \- Watch AppArmor DENIED and ALLOWED Log Messages
.P
.SH "SYNOPSIS"
watch
.SH "DESCRIPTION"
Watches for AppArmor DENIED and ALLOWED log messages\.
.SH "EXAMPLE"
\fBsudo watch\fR
.SH "AUTHOR"
This man page has been written by Patrick Schleizer (adrelanos@whonix\.org)\.
