.\" generated with Ronn-NG/v0.8.0
.\" http://github.com/apjanke/ronn-ng/tree/0.8.0
.TH "APPARMOR\-INFO" "8" "January 2020" "helper-scripts" "helper-scripts Manual"
.SH "NAME"
\fBapparmor\-info\fR \- Shows AppArmor DENIED Log Messages
.P
.SH "SYNOPSIS"
apparmor\-info
.SH "DESCRIPTION"
Shows AppArmor DENIED log messages\.
.SH "AUTHOR"
This man page has been written by Patrick Schleizer (adrelanos@riseup\.net)\.
