.\" generated with Ronn-NG/v0.10.1
.\" http://github.com/apjanke/ronn-ng/tree/0.10.1
.TH "LSMOD\-DETERMINISTIC" "8" "January 2020" "helper-scripts" "helper-scripts Manual"
.SH "NAME"
\fBlsmod\-deterministic\fR \- Shows lsmod, sorted, deterministic
.SH "SYNOPSIS"
lsmod\-deterministic
.SH "DESCRIPTION"
Runs lsmod, shows module names only, deterministic output\.
.SH "RETURN VALUES"
Same as \fBlsmod\fR\.
.SH "EXAMPLE"
\fBlsmod\-deterministic\fR
.SH "AUTHOR"
This man page has been written by Patrick Schleizer (adrelanos@whonix\.org)\.
