.\" generated with Ronn-NG/v0.10.1
.\" http://github.com/apjanke/ronn-ng/tree/0.10.1
.TH "PWCHANGE" "8" "January 2020" "helper-scripts" "helper-scripts Manual"
.SH "NAME"
\fBpwchange\fR \- user friendly account password change utility
.SH "SYNOPSIS"
\fBpwchange\fR
.SH "Description"
Similar to the chpasswd(8) utility but showing the asterisk ("*") symbol while typing the password for better usability\.
.P
Internally using chpasswd(8) to actually change the password\.
.P
Designed for interactive use using command line\. For non\-interactive use in scripts use chpasswd(8) directly\.
.SH "AUTHOR"
This man page has been written by Patrick Schleizer (adrelanos@whonix\.org)\.
