.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "STR_REPLACE" "1" "January 2020" "helper-scripts" "helper-scripts Manual"
.SH "NAME"
\fBstr_replace\fR \- literal search and replace in files (in place) and in STDIN
.SH "SYNOPSIS"
\fBLANG=C str_replace Search Replace File\fR
.SH "DESCRIPTION"
Non\-Regex text search and replace for linux
.P
LANG=C str_replace will enable you to do literal search and replace in files (in place) and in STDIN
.P
No messing with regular expression anymore\. No more \fBsed\fR or \fBawk\fR or \fBperl \-pie\fR\. This handy script written in perl will replace text exactly as you want, No matter it has the so\-called special characters or not\. Just like \fBstr_replace\fR PHP function\.
.SH "RETURN VALUES"
0 ok\.
.P
1 syntax error\.
.P
2 if file not found\.
.SH "EXAMPLE"
To read input from STDIN and write to STDOUT\.
.P
\fBSTDIN | LANG=C str_replace Search Replace\fR
.SH "NOTES"
.IP "\[ci]" 4
Search and replace always case\-sensitive
.IP "\[ci]" 4
Always do global Search and replace
.IP "\[ci]" 4
Don't care about lines\.
.IP "\[ci]" 4
It may work in Windows as well\.
.IP "\[ci]" 4
tested with unicode (I surprised it worked correctly!)
.IP "" 0
.SH "AUTHOR"
This man page has been compiled and modified by Patrick Schleizer (adrelanos@whonix\.org) based contains contents from https://github\.com/Samer\-Al\-iraqi/Linux\-str_replace/blob/master/README\.md Copyright: Copyright (c) 2016 Samer\-Al\-iraqi License: MIT License
