#!/bin/sh
set -eux
git_toplevel="$(git rev-parse --show-toplevel)"
pyrc="${git_toplevel}/pyproject.toml"
pythonpath="${git_toplevel}/usr/lib/python3/dist-packages"
export PYTHONPATH="${pythonpath}${PYTHONPATH+":${PYTHONPATH}"}"
cd "${pythonpath}/stdisplay/"
python3 -m pytest -o 'python_files=*.py' "${@}"
black --config="${pyrc}" --color --diff --check .
find . -type f -name "*.py" -print0 | xargs -0 pylint --rcfile="${pyrc}"
mypy --config-file="${pyrc}" .
