#!/bin/bash
set -eux
git_toplevel="$(git rev-parse --show-toplevel)"
pyrc="${git_toplevel}/pyproject.toml"
pythonpath="${git_toplevel}/usr/lib/python3/dist-packages"
export PYTHONPATH="${pythonpath}${PYTHONPATH+":${PYTHONPATH}"}"

pytest=(python3 -m pytest -o 'python_files=tests/*.py')
black=(black --config="${pyrc}" --color --diff --check)
pylint=(pylint --rcfile="${pyrc}")
mypy=(mypy --config-file="${pyrc}")

cd "${pythonpath}/stdisplay/"
# Ideally, these variables should be ignored by the tests...
NO_COLOR="" COLORTERM="" TERM="xterm-direct" "${pytest[@]}" "${@}"
"${black[@]}" .
find . -type f -name "*.py" -print0 | xargs -0 "${pylint[@]}"
"${mypy[@]}" .

stdin_utils_to_stdout=(stcat stcatn)
stdin_utils_to_file=(sttee stsponge)
stdin_utils=("${stdin_utils_to_stdout[@]}" "${stdin_utils_to_file[@]}")
utils=(stprint stecho "${stdin_utils[@]}")
cd "${git_toplevel}/usr/bin"
"${black[@]}" -- "${utils[@]}"
"${pylint[@]}" -- "${utils[@]}"
for file in "${utils[@]}"; do
  "${mypy[@]}" -- "${file}"
done

for util in "${stdin_utils_to_stdout[@]}"; do
  ./"${util}" <&-
  ./"${util}" - <&-
done
for util in "${stdin_utils_to_file[@]}"; do
  ./"${util}" <&-
done
