#!/bin/bash

## Copyright (C) 2017 - 2018 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -e

/usr/lib/helper-scripts/settings_echo > /run/helper-scripts/settings_environment_file
