#!/bin/bash

## Copyright (C) 2012 - 2021 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

set -e

## provides: check_tor_bootstrap_helper_variables
source /usr/lib/helper-scripts/tor_bootstrap_check.bsh

check_tor_bootstrap_helper_variables

echo "\
GATEWAY_IP=\"$GATEWAY_IP\"
gateway_control_port=\"$gateway_control_port\""
