#!/bin/bash

## Copyright (C) 2017 - 2018 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -e

/usr/lib/anon-shared-helper-scripts/settings_echo > /var/run/anon-shared-helper-scripts/settings_environment_file
