#!/bin/bash

## Copyright (C) 2019 - 2019 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

SUDO_ASKPASS=/usr/lib/helper-scripts/askpass-default sudo -A "$@"
