#!/bin/bash

## Copyright (C) 2014 - 2020 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

exit_handler() {
   if [ "$exit_code" = "" ]; then
      "$0: No exit code set yet. Setting to 1."
   fi
   if [ "$exit_code" = "0" ]; then
      meaning="Set time using Tor consensus middle range time."
   elif [ "$exit_code" = "1" ]; then
      meaning="error"
   elif [ "$exit_code" = "2" ]; then
      meaning="Success, set system clock using Tor certificate lifetime."
   elif [ "$exit_code" = "3" ]; then
      meaning="Setting time using anondate either not possible or not required."
   else
      meaning="Unknown."
   fi
   echo "$0: END: Exiting with code_code '$exit_code' indicating '$meaning'."
   exit "$exit_code"
}

exit_code=1

trap exit_handler EXIT

set_date() {
   echo "$0: INFO: Running: 'date --utc \"+%Y-%m-%d %H:%M:%S\" --set "$time_result"'"
   date --utc "+%Y-%m-%d %H:%M:%S" --set "$time_result"
   exit_code="$?"
}

if [ "$(whoami)" = "sdwdate" ]; then
   anondate_state_folder=/run/sdwdate
elif [ "$(id -u)" = "0" ]; then
   anondate_state_folder=/run/anondate
   mkdir -p "$anondate_state_folder"
else
   echo "$0: ERROR: Must run as root." >&2
   exit 112
fi
anondate_tor_certificate_lifetime_set_file="${anondate_state_folder}/tor_certificate_lifetime_set"

if test -f "$anondate_tor_certificate_lifetime_set_file" ; then
   echo "$0: INFO: Status file '$anondate_tor_certificate_lifetime_set_file' exists."
else
   echo "$0: INFO: Status file '$anondate_tor_certificate_lifetime_set_file' does not yet exist."
fi

echo "$0: INFO: running anondate-get..."

anondate_get_exit_code=0
time_result="$(anondate-get)" || { anondate_get_exit_code="$?" ; true; };

if [ "$anondate_get_exit_code" = "0" ]; then
   echo "$0: INFO: anondate-get returned Tor consensus middle range time."
   set_date
elif [ "$anondate_get_exit_code" = "1" ]; then
   echo "$0: INFO: anondate-get error."
   exit_code=1
elif [ "$anondate_get_exit_code" = "2" ]; then
   if test -f "$anondate_tor_certificate_lifetime_set_file" ; then
      echo "$0: INFO: No, not again setting system clock to Tor certificate lifetime."
   else
      echo "$0: INFO: Yes, setting system clock to Tor certificate lifetime."
      set_date
      echo "$0: INFO: Creating status file '$anondate_tor_certificate_lifetime_set_file'."
      touch "$anondate_tor_certificate_lifetime_set_file"
      echo "$0: INFO: Done, created status file '$anondate_tor_certificate_lifetime_set_file'."

      ## If clock was too fast, restart of Tor is required.
      if [ "$(whoami)" = "sdwdate" ]; then
         echo "$0: INFO: Tor restart using by creating \
/run/sdwdate/request_tor_restart request file."
         touch /run/sdwdate/request_tor_restart
      elif [ "$(id -u)" = "0" ]; then
         sudo -u sdwdate touch /run/sdwdate/request_tor_restart
      else
         echo "$0: ERROR: Tor restart not implemented for users other than \
root and sdwdate." >&2
         exit 112
      fi

      exit_code=2
   fi
fi

exit_code=3
