#!/bin/bash

## Copyright (C) 2014 - 2023 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## See the file COPYING for copying conditions.


if [ "$(id -u)" != "0" ]; then
   echo "$0: ERROR: Must run as root."
   exit 112
fi

cmd_item_list=(
"--has-consensus"
"--current-time-in-valid-range"
"--show-valid-after"
"--show-valid-until"
"--show-middle-range"
"--tor-cert-lifetime-valid"
"--tor-cert-valid-after"
)

for cmd_item in ${cmd_item_list[@]} ; do
   echo "cmd_item: anondate $cmd_item $@"
   output="$(anondate $cmd_item $@)"
   exit_code="$?"
   echo "output: $output"
   echo "exit_code: $exit_code"
   echo "----------"
done
