#!/bin/bash

## Copyright (C) 2014 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.


set -o errexit
set -o nounset
set -o pipefail
set -o errtrace
shopt -s inherit_errexit
shopt -s shift_verbose

if [ "$(id -u)" != "0" ]; then
   printf '%s\n' "$0: ERROR: Must run as root."
   exit 112
fi

cmd_item_list=(
"--has-consensus"
"--current-time-in-valid-range"
"--show-valid-after"
"--show-valid-until"
"--show-middle-range"
"--tor-cert-lifetime-valid"
"--tor-cert-valid-after"
)

for cmd_item in "${cmd_item_list[@]}" ; do
   printf '%s\n' "cmd_item: anondate ${cmd_item} $*"
   output="$(anondate "${cmd_item}" "$@")"
   exit_code="$?"
   printf '%s\n' "output: ${output}"
   printf '%s\n' "exit_code: ${exit_code}"
   printf '%s\n' "----------"
done
