#!/bin/bash

## Copyright (c) 2025 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

set -o errexit
set -o nounset
set -o errtrace
set -o pipefail

source /usr/libexec/helper-scripts/package_installed_check.bsh

get_config_section() {
   local file_name section found_section line
   file_name="$1"
   section="$2"
   found_section='n'
   while read -r line; do
      if [ "${found_section}" = 'y' ]; then
         if [[ "${line}" =~ ^\[.*\]$ ]]; then
            break
         fi
         echo "${line}"
      fi
      if [ "${line}" = "[${section}]" ]; then
         found_section='y'
      fi
   done < "${file_name}"

   true "INFO: Extracted config section '$section' from file '$file_name'."
}

remove_from_config_section() {
   local file_name section remove_line filter_stage
   file_name="$1"
   section="$2"
   remove_line="$3"
   filter_stage='1'
   while read -r line; do
      if [ "${filter_stage}" = '1' ]; then
         echo "${line}"
         if [ "${line}" = "[${section}]" ]; then
            filter_stage='2'
         fi
      elif [ "${filter_stage}" = '2' ]; then
         if [[ "${line}" =~ ^${remove_line}$ ]]; then
            continue
         fi
         echo "${line}"
         if [[ "${line}" =~ ^\[.*\]$ ]]; then
            filter_stage='3'
         fi
      else
         echo "${line}"
      fi
   done < "${file_name}" | sponge -- "${file_name}"

   true "INFO: Removed line '$remove_line' from section '$section' of file '$file_name'."
}

enable_autologin() {
   local user
   user="$1"
   if [ "${lightdm_installed}" = 'yes' ]; then
      mkdir --parents -- /etc/lightdm/lightdm.conf.d
      echo "[Seat:*]
autologin-user=${user}" | sponge -- '/etc/lightdm/lightdm.conf.d/40_autologin.conf'
      true "INFO: Wrote file '/etc/lightdm.conf.d/40_autologin.conf' to enable autologin for user '$user'."
   fi
   if [ "${sddm_installed}" = 'yes' ]; then
      mkdir --parents -- /etc/sddm.conf.d
      echo "[Autologin]
User=${user}" | sponge -- '/etc/sddm.conf.d/z-autologin.conf'
      true "INFO: Wrote file '/etc/sddm.conf.d/z-autologin.conf' to enable autologin for user '$user'."
   fi
}

disable_autologin() {
   local user file_list file_name file_contents
   user="$1"

   if [ "${lightdm_installed}" = 'yes' ]; then
      readarray -t file_list < <(find /etc/lightdm)
      for file_name in "${file_list[@]}"; do
         if ! [ -f "${file_name}" ]; then
            continue
         fi
         sed -i "/^autologin-user=\s*${user}$/d" "${file_name}"
         true "INFO: Removed autologin configuration for user '$user' from file '$file_name'."
         file_contents="$(cat "${file_name}")"
         if [ -z "${file_contents}" ] \
            || [ "${file_contents}" = '[Seat:*]' ]; then
            true "INFO: File '$file_name' contains no meaningful configuration data, removing."
            safe-rm "${file_name}"
         fi
      done
   fi
   if [ "${sddm_installed}" = 'yes' ]; then
      for file_name in /etc/sddm.conf /etc/sddm.conf.d/*; do
         if ! [ -f "${file_name}" ]; then
            continue
         fi
         remove_from_config_section "${file_name}" 'Autologin' "User=${user}"
         true "INFO: Removed autologin configuration for user '$user' from file '$file_name'."
         file_contents="$(cat "${file_name}")"
         if [ -z "${file_contents}" ] \
            || [ "${file_contents}" = '[Autologin]' ]; then
            true "INFO: File '$file_name' contains no meaningful configuration data, removing."
            safe-rm "${file_name}"
         fi
      done
   fi
}

enable_sysmaint_autologin() {
   sed -i '/^sysmaint-autologin=/d' /etc/user-sysmaint-split.conf;
   echo 'sysmaint-autologin=y' >> /etc/user-sysmaint-split.conf;
   true "INFO: Wrote autologin configuration for user 'sysmaint' to file '/etc/user-sysmaint-split.conf'."
}

disable_sysmaint_autologin() {
   sed -i '/^sysmaint-autologin/d' /etc/user-sysmaint-split.conf;
   true "INFO: Removed autologin configuration for user 'sysmaint' from file '/etc/user-sysmaint-split.conf'."
}

autologinchange() {
   local user user_list user_entry found_user autologin_user enable_yn disable_yn
   readarray -t user_list < <(/usr/libexec/helper-scripts/get-user-list)
   echo "Users present on the system:"
   for user_entry in "${user_list[@]}"; do
      echo "   ${user_entry}"
   done

   read -r -p "Enter the username you would like to toggle autologin for: " user

   if [ "$user" = "" ]; then
      echo "ERROR: No username provided. Please specify a username." >&2
      exit 1
   fi

   if ! id "$user" &>/dev/null ; then
      echo "ERROR: User '$user' does not exist. Please check the username and try again." >&2
      exit 1
   fi

   found_user='n'
   for user_entry in "${user_list[@]}"; do
      if [ "${user}" = "${user_entry}" ]; then
         found_user='y'
         break
      fi
   done
   if [ "${found_user}" = 'n' ]; then
      echo "ERROR: User '$user' is not a normal user account. Please check the username and try again." >&2
      exit 1
   fi

   if [[ " ${autologin_users[*]} " =~ " ${user} " ]]; then
      echo "User '$user' is currently configured to automatically log in." >&2
      read -r -p "Would you like to disable autologin? [Y/N] " disable_yn

      if [ "${disable_yn,,}" = 'y' ]; then
         disable_autologin "${user}"
         echo "SUCCESS: Autologin for user '$user' disabled."
      else
         echo "CANCELLED disabling autologin for user '$user'."
      fi
      exit 0
   elif [ "${user}" = 'sysmaint' ]; then
      if [ "${sysmaint_autologin}" = 'y' ]; then
         echo "User 'sysmaint' is currently configured to automatically log in."
         read -r -p "Would you like to disable autologin for sysmaint mode? [Y/N] " disable_yn

         if [ "${disable_yn,,}" = 'y' ]; then
            disable_sysmaint_autologin
            echo "SUCCESS: Autologin for user 'sysmaint' disabled."
         else
            echo "CANCELLED disabling autologin for user 'sysmaint'."
         fi
         exit 0
      else
         echo "User 'sysmaint' is currently NOT configured to automatically log in."
         read -r -p "Would you like to enable autologin for sysmaint mode? [Y/N] " enable_yn

         if [ "${enable_yn,,}" = 'y' ]; then
            enable_sysmaint_autologin
            echo "SUCCESS: Autologin for user 'sysmaint' enabled."
         else
            echo "CANCELLED enabling autologin for user 'sysmaint'."
         fi
         exit 0
      fi
   else
      read -r -p "Are you sure you want to enable autologin for user '$user'? [Y/N] " enable_yn

      if [ "${enable_yn,,}" = 'y' ]; then
         if [ "${#autologin_users[@]}" = '0' ]; then
            for autologin_user in "${autologin_users[@]}"; do
               disable_autologin "${autologin_user}"
            done
         fi
         enable_autologin "${user}"
         echo "SUCCESS: Autologin for user '$user' enabled."
      else
         echo "CANCELLED enabling autologin for user '$user'."
      fi
      exit 0
   fi
}

check_autologin() {
   if [ "${#autologin_users[@]}" = '0' ]; then
      exit 0
   else
      exit 1
   fi
}

if [ "$(id -u)" != "0" ]; then
   echo "ERROR: This must be run as root (sudo)!" >&2
   exit 1
fi

autologin_users_lightdm=()
autologin_users_sddm=()
autologin_users=()
lightdm_installed="$(pkg_installed lightdm && echo 'yes' || echo 'no')"
sddm_installed="$(pkg_installed sddm && echo 'yes' || echo 'no')"

if [ "${lightdm_installed}" = 'yes' ]; then
   ## Ensure that lightdm doesn't have a multi-seat configuration, we can't
   ## safely manage those
   if grep -qri -- '^\[Seat:[^*]' /etc/lightdm; then
      echo "ERROR: Multi-seat lightdm configuration detected, cannot proceed!" >&2
      exit 1
   fi

   readarray -t autologin_users_lightdm < <(
      grep -ri -- '^autologin-user=' /etc/lightdm \
         | grep -v -- 'sysmaint' \
         | awk -F'=' '{ print $NF }' || true
   ) || true
   true "INFO: Collected list of users with lightdm autologin enabled."
fi
if [ "${sddm_installed}" = 'yes' ]; then
   readarray -t autologin_users_sddm < <(
      for file_name in /etc/sddm.conf /etc/sddm.conf.d/*; do
         if ! [ -f "${file_name}" ]; then
            continue
         fi
         get_config_section "${file_name}" 'Autologin'  \
            | grep -- '^User=' \
            | grep -v -- 'sysmaint' \
            | awk -F'=' '{ print $NF }' || true
      done
   ) || true
   true "INFO: Collected list of users with sddm autologin enabled."
fi

readarray -t autologin_users < <(
  IFS=$'\n'
  printf '%s\n%s\n' \
     "${autologin_users_lightdm[*]}" \
     "${autologin_users_sddm[*]}" \
     | sed '/^$/d' \
     | sort -u
)

sysmaint_autologin='n'
if [ ! -f /etc/user-sysmaint-split.conf ]; then
   true "WARNING: File '/etc/user-sysmaint-split.conf' missing, creating empty file in this location"
   touch /etc/user-sysmaint-split.conf
fi
if grep -q -- '^sysmaint-autologin=y$' /etc/user-sysmaint-split.conf; then
   sysmaint_autologin='y'
fi

if [ "${1:-}" = '-c' ]; then
   check_autologin
fi

autologinchange
