#!/bin/bash

## Copyright (C) 2019 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

set -o errexit
set -o nounset
set -o errtrace
set -o pipefail

# shellcheck source=../libexec/helper-scripts/as_root.sh
source /usr/libexec/helper-scripts/as_root.sh

# shellcheck source=../libexec/helper-scripts/has.sh
source /usr/libexec/helper-scripts/has.sh

main() {
   local dkms_mok_dir dkms_mok_public_file dkms_mok_private_file \
      shim_mok_dir shim_mok_public_file shim_mok_private_file \
      mok_keys_present third_party_kernel_module_warning

   printf '%s\n' "INFO: Setting up MOK secure boot keys if necessary..."

   dkms_mok_dir='/var/lib/dkms'
   dkms_mok_public_file="${dkms_mok_dir}/mok.pub"
   dkms_mok_private_file="${dkms_mok_dir}/mok.key"
   shim_mok_dir='/var/lib/shim-signed/mok'
   shim_mok_public_file="${shim_mok_dir}/MOK.der"
   shim_mok_private_file="${shim_mok_dir}/MOK.priv"
   mok_keys_present='n'
   third_party_kernel_module_warning="

Third-party kernel modules and applications that depend on them may not \
function if Secure Boot is enabled. See also:
https://www.kicksecure.com/wiki/Secure_Boot"

   if ! has dkms; then
      printf '%s\n' "ERROR: 'dkms' unavailable. ${third_party_kernel_module_warning}"
      exit 1
   fi

   if [ -f "${dkms_mok_public_file}" ] && [ -f "${dkms_mok_private_file}" ]; then
      printf '%s\n' "INFO: File '${dkms_mok_public_file}' and '${dkms_mok_private_file}' already exist: yes"
      mok_keys_present='y'
   else
      printf '%s\n' "INFO: File '${dkms_mok_public_file}' and '${dkms_mok_private_file}' already exist: no - Creating..."
      if dkms generate_mok; then
         if [ -f "${dkms_mok_public_file}" ] && [ -f "${dkms_mok_private_file}" ]; then
            mok_keys_present='y'
            printf '%s\n' "INFO: File '${dkms_mok_public_file}' and '${dkms_mok_private_file}' successfully created: yes"
         else
            printf '%s\n' "ERROR: File '${dkms_mok_public_file}' and '${dkms_mok_private_file}' successfully created: no
Command 'dkms generate_mok' exited success but failed to create the key files. ${third_party_kernel_module_warning}"
            exit 1
         fi
      else
         printf '%s\n' "WARNING: File '${dkms_mok_public_file}' and '${dkms_mok_private_file}' successfully created: no ${third_party_kernel_module_warning}"
         exit 1
      fi
   fi

   if [ "${mok_keys_present}" != 'y' ]; then
      printf '%s\n' "WARNING: '${dkms_mok_public_file}' and/or \
'${dkms_mok_private_file}' do not exist, and DKMS errored out while trying \
to generate them! ${third_party_kernel_module_warning}"
      exit 1
   fi

   if ! mkdir --parents -- "${shim_mok_dir}"; then
      printf '%s\n' "WARNING: Unable to create directory '${shim_mok_dir}'! \
${third_party_kernel_module_warning}"
      exit 1
   fi

   if ! test -L "${shim_mok_public_file}"; then
      if ! ln -s -- "${dkms_mok_public_file}" "${shim_mok_public_file}"; then
         printf '%s\n' "WARNING: Unable to create symlink from \
'${dkms_mok_public_file}' to '${shim_mok_public_file}'! \
${third_party_kernel_module_warning}"
        exit 1
      fi
   fi

   if ! test -L "${shim_mok_private_file}"; then
      if ! ln -s -- "${dkms_mok_private_file}" "${shim_mok_private_file}" ; then
         printf '%s\n' "WARNING: Unable to create symlink from \
'${dkms_mok_private_file}' to '${shim_mok_private_file}'! \
${third_party_kernel_module_warning}"
         exit 1
      fi
   fi
   printf '%s\n' "INFO: Symlinks '${shim_mok_public_file}' and '${shim_mok_private_file}' exist: yes"

   printf '%s\n' "INFO: Done setting up MOK secure boot keys."
}

as_root
main
