#!/bin/bash

## Copyright (C) 2025 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

set -o errexit
set -o nounset
set -o errtrace
set -o pipefail

export LC_ALL='C'

# shellcheck source=../libexec/helper-scripts/log.sh
source /usr/libexec/helper-scripts/log_run_die.sh

# shellcheck source=../libexec/helper-scripts/as_root.sh
source /usr/libexec/helper-scripts/as_root.sh

# shellcheck source=../libexec/helper-scripts/has.sh
source /usr/libexec/helper-scripts/has.sh

# shellcheck source=../libexec/helper-scripts/secure_boot_enabled_check.bsh
source /usr/libexec/helper-scripts/secure_boot_enabled_check.bsh

# shellcheck source=../sbin/shim-signed-mok-setup
source /usr/sbin/shim-signed-mok-setup

shim_enroll_mok() {
  local do_generate_mok mokutil_sbstate_output \
    secure_boot_enabled_check_retcode

  as_root
  dkms_mok_variables_set

  if ! has dkms; then
    printf '%s\n' "$0: ERROR: The 'dkms' tool is not available, so keys cannot be prepared! Exiting."
    return 1
  fi
  if ! has mokutil; then
    printf '%s\n' "$0: ERROR: The 'mokutil' tool is not available, so keys cannot be enrolled! Exiting."
    return 1
  fi

  secure_boot_enabled_check_retcode='0'
  mokutil_sbstate_output="$(check_secure_boot_enabled)" || secure_boot_enabled_check_retcode="$?"
  if [ "${secure_boot_enabled_check_retcode}" = '1' ]; then
    printf '%s\n' "$0: INFO: Secure Boot is disabled, therefore no need to set up or enroll a MOK. Exiting, ok."
    return 0
  elif [ "${secure_boot_enabled_check_retcode}" = '2' ]; then
    printf '%s\n' "$0: WARNING: Cannot detect Secure Boot state! Exiting."
    printf '%s\n' "$0: WARNING: 'mokutil --sb-state' output:"
    printf '%s\n' "${mokutil_sbstate_output}"
    return 1
  fi
  printf '%s\n' "$0: INFO: Secure Boot is enabled."
  printf '\n'

  printf '%s\n' "\
This tool will help you set up and enroll a Machine Owner Key (MOK). This will
allow you to use software that relies on third-party kernel modules (such as
tirdad and VirtualBox) with Secure Boot enabled.

See also:
https://www.kicksecure.com/wiki/Secure_Boot
"

  if ! read -r -p 'QUESTION: Set up and start enrolling a MOK now? [y/yes/n/no] ' do_generate_mok; then
    printf '%s\n' "$0: INFO: No input available. Exiting without setting up a MOK, ok."
    return 0
  fi

  case "${do_generate_mok,,}" in
    y|yes)
      true
      ;;
    n|no)
      printf '%s\n' "$0: INFO: Exiting without setting up a MOK, as requested by user, ok."
      return 0
      ;;
    *)
      printf '%s\n' "$0: ERROR: Please answer y/yes or n/no."
      return 1
      ;;
  esac

  printf '%s\n' "$0: INFO: Setting up MOK..."
  if ! shim_signed_mok_setup; then
    printf '%s\n' "$0: ERROR: MOK setup failed! Exiting."
    return 1
  fi
  printf '%s\n' "$0: INFO: MOK setup succeeded, ok."

  ## Confusingly, 'mokutil --test-key' returns 1 if the key is already
  ## enrolled, and 0 if it is not.
  if ! log_run notice mokutil --test-key "${dkms_mok_public_file}"; then
    printf '%s\n' "$0: INFO: MOK already enrolled. Exiting, ok."
    return 0
  fi

  printf '%s\n' "\
$0: INFO: Enrolling MOK.
Enter a short, memorable password when prompted. You will only need this once,
to finish the enrollment process."
  if ! log_run notice mokutil --import "${dkms_mok_public_file}"; then
    printf '%s\n' "$0: ERROR: MOK enrollment failed! Exiting."
    return 1
  fi

  printf '%s\n' "\
$0: INFO: MOK enrollment started.
To finish the process:

1. Reboot the system.
2. When a blue 'SHIM UEFI key management' screen appears, press any key, then select 'Enroll MOK'.
3. Then select 'Continue'.
4. Confirm with 'Yes' when prompted.
5. After this, enter the password you set up just now.
6. At this point, you are done. Select 'Reboot'.

To view these steps on a different device, or for more information, see:
https://www.kicksecure.com/wiki/Secure_Boot#Secure_Boot_DKMS_Signing_Key_Enrollment"
}

shim_enroll_mok
