#!/bin/bash

## Copyright (C) 2025 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

set -o errexit
set -o nounset
set -o errtrace
set -o pipefail

command -v stsponge >/dev/null

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$MYDIR"

## Sanity test.
localectl --no-pager >/dev/null

localectl --no-pager list-x11-keymap-layouts  | stsponge ./localectl-list-x11-keymap-layouts-static.txt
localectl --no-pager list-x11-keymap-variants | stsponge ./localectl-list-x11-keymap-variants-static.txt
